### ISSUE TITLE
Missing Documentation 

### ISSUE THREAD

**Issue by engmsaleh** [kirit0-kun/flutter_paymob#1]
Hi, @kirit0-kun Is this a complete Paymob Flutter Plugin for both iOS & Android?
Do you plan to publish it in pub.dev as I didn't see it there?

**Comment by mouEsam** [comment]
Hi
Yes indeed this is a complete plugin for android, iOS, and also web. 
Unfortunately, I have no time to publish it or create a documentation for it.
If you are interested, please let me know.

**Comment by engmsaleh** [comment]
Hi @kirit0-kun Thanks for your reply, I will check it again and if I managed to get all correct, I will document it and try to publish it

**Comment by mouEsam** [comment]
Make sure that the callback url registered in your paymob dashboard includes the text 'post_pay' or 'post-pay' in its path.
